/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_AUTH_URL: string
  readonly VITE_STAGE: string
  readonly VITE_APP: string
  readonly VITE_REALTIME_NOTIFICATIONS_AUTHORIZER: string
  readonly VITE_REALTIME_NOTIFICATIONS_ENDPOINT: string
  readonly VITE_BUILD_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}